name: Node.js - Taskify

on:
  push:
    branches: "main"
    paths-ignore:
      - "*.md"
  pull_request:
    branches: "main"
    paths-ignore:
      - "*.md"

jobs:
  build:
    strategy:
      matrix:
        node: [18.x, 20.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Turbo
        run: npm install -g turbo@latest

      - name: Install
        run: npm install

      - name: Build & Lint
        run: turbo build lint
